# Generated by Django 4.2.27 on 2026-04-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='is_purchased',
        ),
    ]
